apiVersion: v1
kind: Pod
metadata:
  name: opa-allowed
spec:
  containers:
    - name: opa
      image: 071460744267.dkr.ecr.us-east-1.amazonaws.com/test/snyk:latest
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
