apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sallowedrepos
  annotations:
    description: Requires container images to begin with a repo string from a specified
      list.
spec:
  crd:
    spec:
      names:
        kind: K8sAllowedRepos
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            repos:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sallowedrepos

        violation[{"msg": msg}] {
          input.review.object.spec.kind == "Pod"
          image:= input.review.object.spec.containers[_].image
          satisfied := [good | repo = input.parameters.repos[_] ; good = startswith(image, repo)]
          not any(satisfied)
          msg := sprintf("Invalid image repo: <%v>, allowed repos are %v", [image, input.parameters.repos])
        }
