apiVersion: v1
kind: Pod
metadata:
  name: private-image-test-1
spec:
  containers:
    - name: uses-private-image
      image: 071460744267.dkr.ecr.us-east-1.amazonaws.com/test/snyk:latest
      imagePullPolicy: IfNotPresent
      command: [ "echo", "SUCCESS" ]
